// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_ClientCallbackDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface _ClientCallbackDel extends Ice._ObjectDel
{
    void stateDidChange(Message change, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
