// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_ManagerOperationsNC.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface _ManagerOperationsNC
{
    String[] getRooms();

    boolean register(String nick, String password)
        throws UserAlreadyExistException;

    boolean login(String nick, String password)
        throws IncorrectPasswordException,
               UserAlreadyLoggedInException,
               UserNotExistException;

    boolean logout(String nick)
        throws UserNotLoggedInException;

    boolean createRoom(String roomName)
        throws RoomAlreadyExistException;

    boolean removeRoom(String roomName)
        throws RoomNotFoundException;
}
