// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_ManagerDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface _ManagerDel extends Ice._ObjectDel
{
    String[] getRooms(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    boolean register(String nick, String password, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               UserAlreadyExistException;

    boolean login(String nick, String password, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               IncorrectPasswordException,
               UserAlreadyLoggedInException,
               UserNotExistException;

    boolean logout(String nick, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               UserNotLoggedInException;

    boolean createRoom(String roomName, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               RoomAlreadyExistException;

    boolean removeRoom(String roomName, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               RoomNotFoundException;
}
