// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_RoomOperations.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface _RoomOperations
{
    Message[] getHistory(Ice.Current __current)
        throws UserIsNotInRoomException;

    boolean send(String message, Ice.Current __current)
        throws UserIsNotInRoomException;

    boolean join(String roomName, ClientCallbackPrx callback, Ice.Current __current)
        throws RoomNotFoundException,
               UserAlreadyInRoomException;

    boolean leave(String roomName, Ice.Current __current)
        throws RoomNotFoundException,
               UserIsNotInRoomException;
}
