// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_RoomDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface _RoomDel extends Ice._ObjectDel
{
    Message[] getHistory(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               UserIsNotInRoomException;

    boolean send(String message, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               UserIsNotInRoomException;

    boolean join(String roomName, ClientCallbackPrx callback, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               RoomNotFoundException,
               UserAlreadyInRoomException;

    boolean leave(String roomName, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               RoomNotFoundException,
               UserIsNotInRoomException;
}
